import Head from "next/head";
import HeroHeader from "@/components/HeroHeader";

const Home = () => {
  return (
    <>
      <Head>
        <title>LaselessVpn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;600;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <HeroHeader />
      </main>
    </>
  );
};

export default Home;
